const translations = {
    en: {
        nav: {
            about: "About",
            about_us: "Who We Are",
            about_how: "How We Grow",
            about_cert: "Certifications",
            about_team: "Transparency",
            products: "Products",
            prod_fresh: "Fresh Ginger",
            prod_dried: "Dried Ginger",
            prod_infusion: "Ginger Infusions",
            prod_supplement: "Ginger Supplements",
            prod_snack: "Crystallized Snack",
            journey: "The Journey",
            compliance: "Compliance",
            quote: "Request Quote"
        },
        hero: {
            tag: "Premium B2B Export",
            title: "Pure, Organic, Traceable. Premium Peruvian Ginger Crafted for the <span class='serif'>US Market</span>.",
            desc: "Direct from the pristine high-altitude Andean slopes of Peru. Cultivated sustainably, triple-cleaned, and optimized for US food, beverage, and wellness industries.",
            cta_primary: "Explore Our Presentations",
            cta_secondary: "Request Spec Sheets"
        },
        identity: {
            tag: "Corporate Identity",
            title: "A Partnership Built on Trust and Purity",
            mission_title: "Our Mission",
            mission_text: "To supply the US market with food-safe, certified organic ginger through optimized, cold-chain logistics.",
            vision_title: "Our Vision",
            vision_text: "To lead the organic B2B ginger trade in North America by 2030, recognized for our fair-trade partnerships with Andean farmers.",
            val1_title: "Sustainability",
            val1_text: "Eco-friendly agricultural methods protecting soil fertility and high-altitude Andean biodiversity.",
            val2_title: "Absolute Traceability",
            val2_text: "Complete digital logging from cultivation field lot codes to final delivery in US warehouses.",
            val3_title: "Quality Excellence",
            val3_text: "Thorough hand-selection of firm, aromatic rhizomes high in active gingerol concentration.",
            val4_title: "Export Integrity",
            val4_text: "Uncompromised compliance with US regulations, labeling guidelines, and temperature protocols."
        },
        timeline: {
            year: "2026",
            title: "From Field to Global Table",
            text: "Founded in January 2026 by four visionary International Business Administration graduates from UTP, our enterprise was born to revolutionize ginger exports. Facing an immediate global demand for clean-label wellness ingredients, we partnered with smallholder farmers in the Peruvian high-Andes, implementing strict organic practices to secure our first sustainable trade route to the United States."
        },
        catalog: {
            tag: "Product Catalog",
            title: "Our Premium Organic Presentations",
            desc: "Carefully cultivated and processed to retain their intense flavor, crisp texture, and therapeutic properties.",
            
            prod1_title: "Fresh Ginger Rhizomes",
            prod1_desc: "Whole, thoroughly cleaned, uncrushed rhizomes. Highly aromatic with strong gingerol content.",
            prod1_spec1: "Sizing: <strong>Small (30-64g) | Medium (65-80g) | Premium (>81g)</strong>",
            prod1_spec2: "Packaging: <strong>10-15 kg ventilated corrugated cardboard boxes</strong>",

            prod2_title: "Dehydrated Ginger Slices",
            prod2_desc: "Dehydrated premium ginger slices. Extended shelf life for food processing.",
            prod2_spec1: "Moisture Content: <strong>&lt; 12% Max</strong>",
            prod2_spec2: "Packaging: <strong>Polypropylene hermetic bags or jute sacks</strong>",

            prod3_title: "Organic Ginger Infusions",
            prod3_desc: "Premium cut organic ginger tea bags designed for the US wellness market. 100% natural, caffeine-free.",
            prod3_spec1: "Ingredients: <strong>100% Organic Peruvian Ginger</strong>",
            prod3_spec2: "Packaging: <strong>Premium filter bags in eco-friendly boxes</strong>",

            prod4_title: "Ginger Supplements",
            prod4_desc: "Standardized ginger extract capsules (high gingerol percentage) for dietary supplement distributors.",
            prod4_spec1: "Active Ingredients: <strong>High Gingerol Content (5%+)</strong>",
            prod4_spec2: "Packaging: <strong>Amber glass bottles / Bulk wholesale</strong>",

            prod5_title: "Crystallized Ginger Snack",
            prod5_desc: "Sweet and spicy tender ginger chunks preserved in organic cane sugar. Clean label.",
            prod5_spec1: "Ingredients: <strong>Ginger, Organic Cane Sugar</strong>",
            prod5_spec2: "Packaging: <strong>Resealable pouches / Bulk boxes</strong>"
        },
        operations: {
            tag: "Operational Capacity",
            title: "Infrastructure and Logistics",
            desc: "Built to supply US buyers with uninterrupted volume, food safety, and traceable cold-chain precision.",
            field_title: "How We Grow",
            field_text: "Grown at elevations between 1,200m and 1,800m. The intense mountain sun and mineral-rich, pesticide-free volcanic soils give our ginger its characteristic golden pulp and concentrated spicy aroma.",
            pack_title: "Packing Facilities",
            pack_text: "State-of-the-art, sanitized washing and packing facility with automated lines ensuring efficiency and food safety.",
            cold_title: "Cold Storage & Logistics",
            cold_text: "Strict storage protocols in Reefer containers maintained at 12°C to 14°C to prevent mold and dehydration.",
            met1: "250,000 kg",
            met1_lbl: "Fresh Capacity",
            met2: "80,000 kg",
            met2_lbl: "Drying Capacity",
            met3: "12,000 m²",
            met3_lbl: "Facility Area",
            met4: "12 Reefers",
            met4_lbl: "Monthly Export",
            met5: "12°C - 14°C",
            met5_lbl: "Cold Chain Control",
            met6: "1,200 Pallets",
            met6_lbl: "Holding Capacity"
        },
        certifications: {
            tag: "Compliance & Certifications",
            title: "Fully Certified for Smooth Importation",
            desc: "We fulfill all international regulations, giving our US distributors, juice factories, and spice packers absolute administrative and food safety peace of mind.",
            cert1_title: "USDA Organic",
            cert1_text: "100% pesticide-free, natural growing methods required for the US organic sector.",
            cert2_title: "FDA Registered",
            cert2_text: "Full compliance with FDA labeling rules (English ingredient lists, Product of Peru origin stamp, lot tracking, FSVP-ready).",
            cert3_title: "SENASA",
            cert3_text: "Official phytosanitary certificates ensuring every batch is strictly inspected and pest-free.",
            cert4_title: "GlobalG.A.P.",
            cert4_text: "Underlining our adherence to good agricultural practices, food safety, and worker welfare."
        },
        team: {
            tag: "Transparency",
            title: "Executive Team",
            desc: "A visionary group of International Business Administration graduates from UTP, dedicated to revolutionizing global trade and sustainable agriculture.",
            ceo_name: "Jheremi David Jeanpier Chambi Huacachi",
            ceo_role: "CEO & Founder | 22 years old",
            ceo_text: "A brilliant strategist who graduated at the top of his class at UTP. With a PhD in International Relations from Cambridge, Jheremi founded the company in January 2026 to apply advanced global trade theories directly to Peru's agrarian economy.",
            cmo_name: "Tessy Brigith Quispe Patilongo",
            cmo_role: "Chief Marketing Officer | 24 years old",
            cmo_text: "Specialized in global consumer behavior at UTP, Tessy is the creative force behind our Rhode-inspired digital identity, elevating organic ginger from an agricultural commodity to a premium wellness brand in the US.",
            cso_name: "Marco Antonio Lima Narciso",
            cso_role: "Chief Sales Officer | 25 years old",
            cso_text: "An expert negotiator shaped by UTP's international trade programs. Marco has brokered distribution partnerships with organic supermarkets and wellness brands across the US East Coast.",
            cfo_name: "Fabricio Eduardo Ortega Torres",
            cfo_role: "Chief Financial Officer | 22 years old",
            cfo_text: "A mathematical mind who excelled in corporate finance at UTP. Fabricio manages our financial structure, ensuring secure importer transactions and fair compensation for our farming partners."
        },
        contact: {
            tag: "Contact Exporter",
            title: "Partner With Us. Request Quotes & <span class='serif'>Samples</span>.",
            desc: "Are you a US distributor, procurement manager, healthy beverage manufacturer, or organic spice packer? Fill out our brief B2B request, and our export logistics team will get back to you with specs and a customized quote within 24 hours.",
            offices: "Offices",
            phone: "Phone",
            form_name: "Full Name",
            form_email: "Business Email",
            form_company: "Company Name",
            form_phone: "Phone Number",
            form_presentation: "Requested Presentation",
            opt_fresh: "Fresh Ginger Rhizomes",
            opt_dried: "Dried/Dehydrated Slices",
            opt_infusion: "Ginger Infusions",
            opt_supplement: "Ginger Supplements",
            opt_snack: "Crystallized Snack",
            form_message: "Your Message / Special Requests",
            form_placeholder: "Estimate volume, target US port, certificate needs...",
            submit: "Request Technical Specs & B2B Quotations",
            submitting: "Sending Request..."
        },
        footer: {
            desc: "Premium organic agricultural products exported from the Peruvian Andes to global markets.",
            links_title: "Quick Links",
            resources_title: "Resources",
            link_samples: "Request Samples",
            link_pdf: "Download Specs (PDF)",
            disclaimer: "<strong>FDA Disclaimer:</strong> The information provided on this website is for informational B2B purposes only. Our products are agricultural raw materials certified under organic standards and are registered with the US FDA. Final product packaging, safety labeling, and customs clearances conform to federal regulations.",
            bottom: "Crafted with Organic Passion. Lima, Peru."
        },
        toast: {
            success: "Request submitted successfully! We will contact you soon."
        }
    },
    es: {
        nav: {
            about: "Acerca de",
            about_us: "Nosotros",
            about_how: "Cómo Cultivamos",
            about_cert: "Certificaciones",
            about_team: "Transparencia",
            products: "Productos",
            prod_fresh: "Jengibre Fresco",
            prod_dried: "Jengibre Seco",
            prod_infusion: "Infusiones",
            prod_supplement: "Suplementos",
            prod_snack: "Snack Cristalizado",
            journey: "El Proceso",
            compliance: "Certificaciones",
            quote: "Cotizar"
        },
        hero: {
            tag: "Exportación B2B Premium",
            title: "Puro, Orgánico, Trazable. Jengibre Peruano de Exportación para el <span class='serif'>Mercado de EE.UU.</span>",
            desc: "Directo de las laderas andinas de Perú. Cultivado de forma sostenible, con triple lavado y optimizado para las industrias de alimentos, bebidas y bienestar en EE.UU.",
            cta_primary: "Ver Presentaciones",
            cta_secondary: "Ficha Técnica"
        },
        identity: {
            tag: "Identidad Corporativa",
            title: "Una Alianza Basada en Confianza y Pureza",
            mission_title: "Nuestra Misión",
            mission_text: "Abastecer al mercado de EE.UU. con jengibre orgánico certificado e inocuo a través de logística optimizada de cadena de frío.",
            vision_title: "Nuestra Visión",
            vision_text: "Liderar el comercio B2B de jengibre orgánico en Norteamérica para 2030, reconocidos por nuestras alianzas de comercio justo con agricultores andinos.",
            val1_title: "Sostenibilidad",
            val1_text: "Métodos agrícolas ecológicos que protegen la fertilidad del suelo y la biodiversidad andina.",
            val2_title: "Trazabilidad Absoluta",
            val2_text: "Registro digital completo desde los códigos de lote de cultivo hasta la entrega final en almacén.",
            val3_title: "Excelencia de Calidad",
            val3_text: "Rigurosa selección manual de rizomas firmes y aromáticos con alta concentración de gingerol activo.",
            val4_title: "Integridad de Exportación",
            val4_text: "Cumplimiento estricto de las regulaciones de EE.UU., guías de etiquetado y protocolos de frío."
        },
        timeline: {
            year: "2026",
            title: "Del Campo a la Mesa Global",
            text: "Fundada en enero de 2026 por cuatro visionarios egresados de Administración de Negocios Internacionales de la UTP, nuestra empresa nació para revolucionar la exportación de jengibre. Ante la demanda global de ingredientes puros, nos asociamos con pequeños agricultores en los altos Andes peruanos, implementando prácticas orgánicas para asegurar nuestra primera ruta sostenible a EE.UU."
        },
        catalog: {
            tag: "Catálogo de Productos",
            title: "Nuestras Presentaciones Orgánicas Premium",
            desc: "Cuidadosamente cultivados y procesados para conservar su intenso sabor, textura crujiente y propiedades terapéuticas.",
            
            prod1_title: "Jengibre Fresco",
            prod1_desc: "Rizomas enteros, rigurosamente lavados. Altamente aromáticos con fuerte contenido de gingerol.",
            prod1_spec1: "Calibre: <strong>Pequeño (30-64g) | Mediano (65-80g) | Premium (>81g)</strong>",
            prod1_spec2: "Empaque: <strong>Caja de cartón ventilada de 10-15 kg</strong>",

            prod2_title: "Jengibre Seco en Rodajas",
            prod2_desc: "Rodajas deshidratadas premium. Vida útil extendida para procesamiento de alimentos.",
            prod2_spec1: "Humedad: <strong>&lt; 12% Máx</strong>",
            prod2_spec2: "Empaque: <strong>Bolsas herméticas de polipropileno o sacos de yute</strong>",

            prod3_title: "Infusiones de Jengibre",
            prod3_desc: "Bolsitas de té de jengibre orgánico diseñadas para el mercado wellness de EE.UU. 100% natural, sin cafeína.",
            prod3_spec1: "Ingredientes: <strong>100% Jengibre Peruano Orgánico</strong>",
            prod3_spec2: "Empaque: <strong>Bolsas filtrantes premium en cajas ecológicas</strong>",

            prod4_title: "Suplemento de Jengibre",
            prod4_desc: "Cápsulas de extracto estandarizado (alto % de gingerol) para distribuidores de suplementos.",
            prod4_spec1: "Ingredientes Activos: <strong>Alto Contenido de Gingerol (5%+)</strong>",
            prod4_spec2: "Empaque: <strong>Frascos de vidrio ámbar / Venta al por mayor</strong>",

            prod5_title: "Snack de Jengibre Cristalizado",
            prod5_desc: "Trozos de jengibre tiernos, dulces y picantes conservados en azúcar de caña orgánica. Etiqueta limpia.",
            prod5_spec1: "Ingredientes: <strong>Jengibre, Azúcar de Caña Orgánica</strong>",
            prod5_spec2: "Empaque: <strong>Bolsas resellables / Cajas a granel</strong>"
        },
        operations: {
            tag: "Capacidad Operativa",
            title: "Nuestra Infraestructura y Logística",
            desc: "Diseñada para abastecer a compradores de EE.UU. con volumen continuo, inocuidad alimentaria y trazabilidad de frío.",
            field_title: "Cómo Cultivamos",
            field_text: "Cultivado a elevaciones entre 1,200m y 1,800m. El intenso sol de montaña y los suelos volcánicos ricos en minerales dan a nuestro jengibre su pulpa dorada y aroma picante.",
            pack_title: "Instalaciones de Empaque",
            pack_text: "Planta de empaque de vanguardia con líneas automatizadas que aseguran eficiencia e inocuidad.",
            cold_title: "Almacenamiento y Cadena de Frío",
            cold_text: "Protocolos estrictos en contenedores Reefer de 12°C a 14°C para prevenir hongos y deshidratación.",
            met1: "250,000 kg",
            met1_lbl: "Capacidad Mensual Fresco",
            met2: "80,000 kg",
            met2_lbl: "Capacidad de Secado",
            met3: "12,000 m²",
            met3_lbl: "Área de Planta",
            met4: "12 Reefers",
            met4_lbl: "Exportación Mensual",
            met5: "12°C - 14°C",
            met5_lbl: "Control Cadena de Frío",
            met6: "1,200 Pallets",
            met6_lbl: "Capacidad de Almacén"
        },
        certifications: {
            tag: "Cumplimiento y Certificaciones",
            title: "Totalmente Certificado para una Importación Fluida",
            desc: "Cumplimos con toda la normativa internacional para brindar a nuestros distribuidores tranquilidad absoluta.",
            cert1_title: "USDA Organic",
            cert1_text: "100% libre de pesticidas, métodos naturales requeridos para el sector orgánico de EE.UU.",
            cert2_title: "FDA Registered",
            cert2_text: "Cumplimiento con normas de la FDA (ingredientes en inglés, sello Product of Peru, FSVP).",
            cert3_title: "SENASA",
            cert3_text: "Certificados fitosanitarios oficiales asegurando que cada lote esté libre de plagas.",
            cert4_title: "GlobalG.A.P.",
            cert4_text: "Subraya nuestra adherencia a buenas prácticas agrícolas, inocuidad y bienestar laboral."
        },
        team: {
            tag: "Transparencia",
            title: "Equipo Ejecutivo",
            desc: "Un grupo visionario de egresados de Administración de Negocios Internacionales de la UTP, dedicado a revolucionar el comercio.",
            ceo_name: "Jheremi David Jeanpier Chambi Huacachi",
            ceo_role: "CEO y Fundador | 22 años",
            ceo_text: "Un brillante estratega graduado con honores en la UTP. Con un doctorado en Relaciones Internacionales en Cambridge, Jheremi fundó la empresa en 2026 para aplicar teorías globales al agro peruano.",
            cmo_name: "Tessy Brigith Quispe Patilongo",
            cmo_role: "Directora de Marketing | 24 años",
            cmo_text: "Especializada en comportamiento global, Tessy es la fuerza creativa detrás de nuestra identidad inspirada en Rhode, elevando el jengibre orgánico a una marca wellness premium.",
            cso_name: "Marco Antonio Lima Narciso",
            cso_role: "Director de Ventas | 25 años",
            cso_text: "Un negociador experto forjado en la UTP. Marco ha concretado alianzas de distribución con supermercados orgánicos y marcas de bebidas en toda la costa este de EE.UU.",
            cfo_name: "Fabricio Eduardo Ortega Torres",
            cfo_role: "Director Financiero | 22 años",
            cfo_text: "Una mente matemática que sobresalió en finanzas corporativas en la UTP. Fabricio gestiona nuestra estructura financiera, asegurando transacciones justas para importadores y agricultores."
        },
        contact: {
            tag: "Contacto de Exportación",
            title: "Asóciese con Nosotros. Solicite Cotizaciones y <span class='serif'>Muestras</span>.",
            desc: "¿Es distribuidor en EE.UU. o fabricante de bebidas? Complete este formulario B2B y nuestro equipo le enviará fichas técnicas y cotización en menos de 24 horas.",
            offices: "Oficinas",
            phone: "Teléfono",
            form_name: "Nombre Completo",
            form_email: "Correo Corporativo",
            form_company: "Nombre de la Empresa",
            form_phone: "Teléfono de Contacto",
            form_presentation: "Presentación de Interés",
            opt_fresh: "Jengibre Fresco",
            opt_dried: "Jengibre Seco",
            opt_infusion: "Infusiones",
            opt_supplement: "Suplementos",
            opt_snack: "Snack Cristalizado",
            form_message: "Mensaje / Requerimientos Especiales",
            form_placeholder: "Volumen estimado, puerto de destino en EE.UU., certificados necesarios...",
            submit: "Solicitar Fichas Técnicas y Cotización B2B",
            submitting: "Enviando Solicitud..."
        },
        footer: {
            desc: "Productos agrícolas orgánicos de alta calidad exportados desde los Andes peruanos hacia mercados globales.",
            links_title: "Enlaces Rápidos",
            resources_title: "Recursos",
            link_samples: "Solicitar Muestras",
            link_pdf: "Descargar Ficha (PDF)",
            disclaimer: "<strong>Descargo de responsabilidad de la FDA:</strong> La información provista es solo para fines informativos B2B. Nuestros productos están certificados y registrados ante la FDA de EE.UU.",
            bottom: "Diseñado con Pasión Orgánica. Lima, Perú."
        },
        toast: {
            success: "¡Solicitud enviada con éxito! Nos pondremos en contacto pronto."
        }
    }
};
